### ISSUE TITLE
Typo in a template

### ISSUE THREAD

**Issue by krau5** [kingsman-fullstackdev/kingsman-fullstackdev.github.io#1]
[Typo link](https://github.com/WHAHA-HA/WHAHA-HA.github.io/blob/main/index.html#L421) + typo image
<img width="210" alt="image" src="https://user-images.githubusercontent.com/52201020/193155427-998875b5-4743-44ff-ac38-29a73930d7e8.png">

One more typo:
https://github.com/WHAHA-HA/WHAHA-HA.github.io/blob/main/index.html#L1096

**Comment by WHAHA-HA** [comment]
Hi, thanks for your advice. Please let me know why you think so.
